- hosts: all
  become: yes
  tasks:
    - name: create the 'adnan' user
      user: name=adnan append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'adnan' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'adnan ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the adnan user
      authorized_key: user=adnan key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
